### ISSUE TITLE
Random undefined method `accessor' exceptions

### ISSUE THREAD

**Issue by mdi** [palkan/store_attribute#38]
### Tell us about your environment

**Ruby Version:**
3.2.2

**Rails Version:**
7.1-edge

**PostgreSQL Version:**
15

**Store Attribute Version:**
1.1.1

### What did you do?
Refreshing a page, seemingly after making any code change, I get exceptions like:
```
undefined method `accessor' for #<ActiveModel::Type::Value:0x0000ffffa41a7a08 @precision=nil, @scale=nil, @limit=nil>
```
restarting the web server fixes it.

### What did you expect to happen?
No exceptions.

### What actually happened?
See above.

**Comment by palkan** [comment]
Thanks for the report.

Did it happen before you upgraded to 1.1.1? Or, if it's possible, could you please check if the problem persist if you downgrade to 1.1.0?

It seems relevant to the recently introduced change: https://github.com/palkan/store_attribute/pull/37

/cc @mrexox

**Comment by mdi** [comment]
The issue still persists with v1.1.0.

**Comment by palkan** [comment]
Thanks.

May I ask to you to check if the issue persist if you downgrade Rails to 7.0.x? (Or vice versa, if you try the latest main).

**Comment by georgebellos** [comment]
It also happens to rails 7.0.+

**Comment by palkan** [comment]
Thanks @georgebellos!

@mdi @georgebellos Could you please provide a more details stacktrace for the exception? What triggers it? That would help us to quicker come up with the reproduction and the fix (eventually).

And just to confirm: does setting `cache_classes = true` in the configuration fix the problem? (So, it only happens when the code is being reloaded)

**Comment by baygeldin** [comment]
JFYI (maybe it helps in finding the root cause): we hit this issue when running a migration locally that added a JSONB field we were going to use via `store_attribute`. I randomly decided to add a `store :whatever, coder: JSON` before any `store_attribute` setup and it worked for whatever reason (I didn't dig into the issue since the workaround worked by a blind luck).

```ruby
  store :whatever, coder: JSON # adding this line got rid of the error
  
  self.store_attribute_unset_values_fallback_to_default = true

  store_attribute :whatever, :foo, :json, default: [], prefix: 'whtvr'
  store_attribute :whatever, :bar, :string, default: nil, prefix: 'whtvr'
```

**Comment by alois-gaucher** [comment]
Hello there,

I keep getting the same error message when seeding the database with demo data.
```
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x0000ffff722412c0 @precision=nil, @scale=nil, @limit=nil>
```

Moving back to 1.1.0 changes the error message to
 ```
NoMethodError: undefined method `symbolize_keys' for true:TrueClass
/home/docker//app/models/application_record.rb:192:in `block in compute_store_defaults_for'
/home/docker//app/models/application_record.rb:191:in `each'
/home/docker//app/models/application_record.rb:191:in `compute_store_defaults_for'
/home/docker//app/models/application_record.rb:214:in `block in compute_store_defaults'
/home/docker//app/models/application_record.rb:213:in `each_key'
/home/docker//app/models/application_record.rb:213:in `compute_store_defaults'
```

**Comment by palkan** [comment]
Hey everyone,

Unfortunately, I wasn't able to reproduce this problem (tried both Rails reloading and running migrations). So, any reproduction script would be helpful to fix this.

**Comment by ba1ash** [comment]
Hi there,
I experienced the same issue. **Rails** version  7.0.8, **Ruby** version 3.2.1, **Store Attribute** version 1.1.1, **PostgreSQL version** 13.9.
For me it happens when I try to use a model with `store_attribute` defined on a column that is not yet in the database.
For example when the model is used in an old migration when the column has not been created yet.
Solution in my case was to replace model usages with raw sql queries.

If I compare the behavior with `store_accessor` defined on non yet existing column the model instance can be created and seems to be operable and raises the following error only when I use the accessor explicitly.
```ruby
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x00007f9f59bce738 @precision=nil, @scale=nil, @limit=nil>
from /usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/store.rb:217:in `store_accessor_for'
```
with `store_attribute` the model is not working at all without the database column. Calls like: `Model.new`  `Mode.where(id: 123)` fail instantly with:
```ruby 
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x00007f370b0cf7f8 @precision=nil, @scale=nil, @limit=nil>
from /usr/local/bundle/gems/store_attribute-1.1.1/lib/store_attribute/active_record/type/typed_store.rb:33:in `initialize'
```

I hope this will help to reproduce the issue @palkan.

**Comment by palkan** [comment]
Great news: I got a reproduction test! (thanks to @ba1ash again). Stay tuned for the fix and a patch release.
